name: Publish latest updates
on:
  workflow_dispatch:

jobs:
  webhook_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Parse version
        id: parse-version
        run: |
          TAG=${{ steps.get-latest-tag.outputs.tag }}
          VERSION=${TAG:1}
          
          echo "Latest tag: ${TAG}"
          echo "Latest version: ${VERSION}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
 
      - name: Trigger webhook
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: PacketBooks
          embed-title: PacketBooks has been updated to ${{ steps.parse-version.outputs.version }}!
          embed-color: 14706969
          embed-description: |
            Download the latest release here:

            <:modrinth:1016015520216141855> [Modrinth](https://modrinth.com/plugin/packetbooks/version/${{ steps.parse-version.outputs.version }})
            <:hangar:1099459442866667581> [Hangar](https://hangar.papermc.io/Strokkur424/PacketBooks/versions/${{ steps.parse-version.outputs.version }})
            <:github:927433909254369291> [GitHub](https://github.com/Strokkur424/PacketBooks/releases/tag/${{ steps.get-latest-tag.outputs.tag }})
          embed-thumbnail-url: https://raw.githubusercontent.com/Strokkur424/PacketBooks/main/public/packetbooks.png
          embed-timestamp: ${{ steps.date.outputs.date }}
